# Feature Enginering

In [5]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("cleaned_data.csv")
df

,customer_id,age,gender,city,income,education,experience_years,monthly_spending,credit_score,signup_date,has_credit_card,loan_amount,employment_type,defaulted
0,C100000,18.0,Male,faisalabad,97203.41,Bachelor,33,34323.67,728.0,2020-01-01,Yes,162409.81000,Unemployed,0
1,C100001,56.0,Female,islamabad,132084.64,Matric,20,36955.51,439.0,2020-02-01,Yes,207532.68000,Government,0
2,C100002,51.0,Female,Lahore,39789.24,Bachelor,26,30520.91,516.0,2020-03-01,Yes,261934.54000,Government,0
3,C100003,21.0,Female,islamabad,110957.74,Matric,23,34385.96,520.0,2020-04-01,No,247704.90777,Student,1
4,C100004,69.0,Female,rawalpindi,127385.88,Master,18,34126.80,715.0,2020-05-01,No,92532.55000,Business,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,C102995,52.0,Male,Lahore,61720.95,PhD,22,33887.96,744.0,2028-03-14,Yes,302254.75000,Government,0
2986,C102996,57.0,Male,rawalpindi,39240.38,PhD,14,50459.38,448.0,2028-03-15,Yes,312313.61000,Unemployed,0
2987,C102997,60.0,Male,rawalpindi,114709.11,Master,13,79268.23,334.0,2028-03-16,Yes,325664.77000,Private,0
2988,C102998,51.0,Male,Lahore,131678.22,Intermediate,31,41027.35,550.0,2028-03-17,No,322692.25000,Government,1
2989,C102999,56.0,Female,rawalpindi,47212.42,Matric,21,32045.86,702.0,2028-03-18,No,268983.69000,Government,0

In [7]:
df.isnull().sum()

customer_id         0
age                 0
gender              0
city                0
income              0
education           0
experience_years    0
monthly_spending    0
credit_score        0
signup_date         0
has_credit_card     0
loan_amount         0
employment_type     0
defaulted           0
dtype: int64

In [8]:
df.to_csv("cleaned_data.csv", index=False)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2990 entries, 0 to 2989
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2990 non-null   str
 1   age               2990 non-null   float64
 2   gender            2990 non-null   str
 3   city              2990 non-null   str
 4   income            2990 non-null   float64
 5   education         2990 non-null   str
 6   experience_years  2990 non-null   int64
 7   monthly_spending  2990 non-null   float64
 8   credit_score      2990 non-null   float64
 9   signup_date       2990 non-null   str
 10  has_credit_card   2990 non-null   str
 11  loan_amount       2990 non-null   float64
 12  employment_type   2990 non-null   str
 13  defaulted         2990 non-null   int64
dtypes: float64(5), int64(2), str(7)
memory usage: 327.2 KB

In [12]:
df

,customer_id,age,gender,city,income,education,experience_years,monthly_spending,credit_score,signup_date,has_credit_card,loan_amount,employment_type,defaulted
0,C100000,18.0,Male,faisalabad,97203.41,Bachelor,33,34323.67,728.0,2020-01-01,Yes,162409.81000,Unemployed,0
1,C100001,56.0,Female,islamabad,132084.64,Matric,20,36955.51,439.0,2020-02-01,Yes,207532.68000,Government,0
2,C100002,51.0,Female,Lahore,39789.24,Bachelor,26,30520.91,516.0,2020-03-01,Yes,261934.54000,Government,0
3,C100003,21.0,Female,islamabad,110957.74,Matric,23,34385.96,520.0,2020-04-01,No,247704.90777,Student,1
4,C100004,69.0,Female,rawalpindi,127385.88,Master,18,34126.80,715.0,2020-05-01,No,92532.55000,Business,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,C102995,52.0,Male,Lahore,61720.95,PhD,22,33887.96,744.0,2028-03-14,Yes,302254.75000,Government,0
2986,C102996,57.0,Male,rawalpindi,39240.38,PhD,14,50459.38,448.0,2028-03-15,Yes,312313.61000,Unemployed,0
2987,C102997,60.0,Male,rawalpindi,114709.11,Master,13,79268.23,334.0,2028-03-16,Yes,325664.77000,Private,0
2988,C102998,51.0,Male,Lahore,131678.22,Intermediate,31,41027.35,550.0,2028-03-17,No,322692.25000,Government,1
2989,C102999,56.0,Female,rawalpindi,47212.42,Matric,21,32045.86,702.0,2028-03-18,No,268983.69000,Government,0